apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./cluster/releases/namespaces
  prune: true
  wait: true
  timeout: 2m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./cluster/releases/prometheus
  prune: true
  wait: true
  timeout: 2m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./cluster/releases/prometheus/resources
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./cluster/releases/nginx-ingress-controller
  prune: true
  wait: true
  timeout: 2m
