apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  interval: 1m0s
  url: https://charts.bitnami.com/bitnami

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  chart:
    spec:
      chart: nginx-ingress-controller
      version: "9.1.26"
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress-controller
  interval: 1m0s
  releaseName: nginx-ingress-controller
  targetNamespace: nginx-ingress-controller
